
ar: {
    selectLanguage: "اختر لغتك:",
    welcome: "مرحبا!",
    username: "اسم المستخدم:",
    phone: "رقم الهاتف:",
    continue: "استمرار",
    back: "العودة إلى قائمة اللغات",
    propertyTitle: "العقارات المتاحة:",
    save: "حفظ كملف PDF",
    tableHeaders: [
      "رقم",
      "العقار",
      // "العنوان",
      // "الوصف",
      "المساحة",
      "السعر",
      // "صورة",
      // "فيديو",
      "تأكيد",
      "اقتراح",
      "إلغاء"
    ],
    validate: "تأكيد",
    propose: "اقتراح",
    cancel: "إلغاء",
    noDesire: "غير مهتم",
    fillAll: "يرجى ملء جميع الحقول.",
    invalidPhone: "رقم الهاتف غير صالح.",
    invalidPrice: "سعر غير صالح.",
    actionRequired: "يرجى اختيار إجراء لكل عقار.",
    pdfSaved: "تم حفظ ملف PDF باسم :",
    purchaseProcedureTitle: "إجراءات الشراء :",

purchaseProcedure: [
      "1. تحقق من العقارات والاختيارات في الجدول.",
      "2. اتصل بقسم المبيعات على الرقم المذكور.",
      "3. سيقوم المستشار بمساعدتك لإتمام المعاملة.",
      "4. ستتلقى رسالة تأكيد عبر البريد الإلكتروني.",
      "5. أرسل عرضك عبر البريد الإلكتروني أو الواتساب.",
      "شكراً لثقتك."
    ],
  
    summaryTitle: "ملخص الاختيارات",
    nameLabel: "الاسم :",
    phoneLabel: "الهاتف :",
    dateLabel: "تاريخ الإدخال :",
    photoText: "صورة",
    videoText: "فيديو"
  },
  es: {
    selectLanguage: "Elija su idioma:",
    welcome: "¡Bienvenido!",
    username: "Nombre de usuario:",
    phone: "Número de teléfono:",
    continue: "Continuar",
    back: "Volver al menú de idiomas",
    propertyTitle: "Propiedades disponibles:",
    save: "Guardar como PDF",
    tableHeaders: [
      "N°",
      "Propiedad",
      //    "Título",
      //     "Descripción",
      "Superficie",
      "Precio",
      //      "Foto",
      //     "Vídeo",
      "Validar",
      "Propuesta",
      "Cancelar"
    ],
    validate: "Validar",
    propose: "Proponer",
    cancel: "Cancelar",
    noDesire: "No interesado",
    fillAll: "Por favor, complete todos los campos.",
    invalidPhone: "Número de teléfono inválido.",
    invalidPrice: "Precio inválido.",
    actionRequired: "Por favor, seleccione una acción para cada propiedad.",
    pdfSaved: "PDF guardado como:",
    purchaseProcedureTitle: "Procedimiento de compra:",
    purchaseProcedure:
      "1. Verifique las propiedades y selecciones en la tabla.\n" +
      "2. Contacte a nuestro departamento de ventas al número indicado.\n" +
      "3. Un asesor le ayudará a finalizar la transacción.\n" +
      "4. Recibirá un correo electrónico de confirmación con los detalles.\n" +
      "Gracias por su confianza.",
    summaryTitle: "Resumen de selecciones",
    nameLabel: "Nombre:",
    phoneLabel: "Teléfono:",
    dateLabel: "Fecha de ingreso:",
    photoText: "Foto",
    videoText: "Vídeo"
  },
